# Generated by Django 5.2 on 2025-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "content",
                    models.TextField(
                        help_text="Текст блога", verbose_name="Содержимое"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="photos/blogs",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Дата создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True,
                        help_text="Дата изменения",
                        verbose_name="Дата последнего изменения",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": [
                    "title",
                    "is_published",
                    "created_at",
                    "updated_at",
                    "views_count",
                ],
            },
        ),
    ]
