# Generated by Django 5.2 on 2025-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_add_view_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
