# Generated by Django 5.2 on 2025-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="can_unpublish_product",
            field=models.BooleanField(
                default=False,
                help_text="Может отменить публикацию продукта",
                verbose_name="Может отменить публикацию продукта",
            ),
        ),
    ]
