# Generated by Django 5.2 on 2025-05-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_can_unpublish_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="can_unpublish_product",
        ),
    ]
